spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/payment?serverTimezone=GMT
    username: root
    password: monkey2016
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //

  #redis????
  redis:
    host: 127.0.0.1
    port: 6379
